"""initial tables

Revision ID: b6bf60fce115
Revises: 
Create Date: 2025-08-20 15:50:59.700989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bf60fce115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=25), nullable=False),
    sa.Column('lastname', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phoneno', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('memberId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneno')
    )
    op.create_table('loanapps',
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('monthrepay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['users.memberId'], ),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.create_table('payments',
    sa.Column('paymentId', sa.Integer(), nullable=False),
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('payname', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('receipt', sa.String(length=18), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['users.memberId'], ),
    sa.PrimaryKeyConstraint('paymentId'),
    sa.UniqueConstraint('receipt')
    )
    op.create_table('shares',
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('dividends', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('penalties', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['users.memberId'], ),
    sa.PrimaryKeyConstraint('memberId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    op.drop_table('payments')
    op.drop_table('loanapps')
    op.drop_table('users')
    # ### end Alembic commands ###
